apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./ip-reconciler-job.yaml
- ./daemonset-install.yaml
- ./whereabouts.cni.cncf.io_ippools.yaml
- ./whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml

transformers:
  - patch-ip-reconciler-job.yaml
