# TODO: remove after whereabouts contains https://github.com/k8snetworkplumbingwg/whereabouts/pull/150
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: patch-ip-reconciler-job
labels:
  app: whereabouts
fieldSpecs:
- path: spec/jobTemplate/spec/template/metadata/labels
  create: true
  kind: CronJob
  metadata:
    name: ip-reconciler

